### PR TITLE
new maintainer (Lars Kruse)

### PR DESCRIPTION
**Pull request by sumpfralle**
Dear mopidy maintainers,

I would like to take over maintainance of the beets plugin for mopidy. It is currently unmaintained.

See my currently open pull requests:
* #15 
* #16 
* #17 

Additionally the issues #4 and #10 are handled in my [development branch](https://github.com/sumpfralle/mopidy-beets/tree/working) of the plugin.

I have some more plans regarding improved browse and search behaviour.

Cheers,
Lars

### CODE REVIEW

**Comment by jodal** [comment]
I'm so happy to have someone take on responsibility for mopidy-beets. Thanks! Welcome on board :-)

**Comment by jodal** [comment]
I've given you write access to the repo. Do you have a PyPI user which I can give permissions to do releases of Mopidy-Beets?

**Comment by sumpfralle** [comment]
I am happy to take over this plugin. Thank you for granting write access!
My pypi username is "sumpfralle".

**Comment by jodal** [comment]
You should have maintainer access on PyPI now. Thanks again :-)

I suggest bumping the version number to 3.0 for the next release, just to mark the split between "old and unmaintained" and the "new" Mopidy-Beets ;-)

**Comment by sumpfralle** [comment]
This sounds like a good approach - I will do it this way.
Thank you!

**Pull request merged**
